# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d18a02760191cd3025b24640146db3f0d3a081f105fae46b327f3f2c62fee05f9c96188fdc692566e81bbddfb65c7078d40385cfeb6ad25971602b89934fe9ab

test:
  secret_key_base: 6230ecd2718d9cd315b6e6f284d042c67fa45d2fd4085a285d07748a3a25b85c132baf0dd19f737367361fc5c5424f00e65f30c1f181a4c60510b9275f75d7ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
